services:
  remotedesktop:
    hostname: remotedesktop
    env_file: .env
    build: remotedesktop/
    restart: unless-stopped
    image: ronaldvk90/remotedesktop:latest
    ports:
      - 3389:3389/tcp
    cap_add:
      - SYS_ADMIN
    volumes:
      - etc:/etc
      - home:/home
      - /etc/localtime:/etc/localtime:ro
volumes:
  etc:
  home: